In [12]:
# 1. 다음 데이터 프레임을 ndarray, 리스트, 딕셔너리 형태로 변경하여 array1, list1, dict1 변수에 저장하시오.
import seaborn as sns
df = sns.load_dataset('iris')
array1 = df.values
list1 = df.values.tolist()
dict1 = df.to_dict()

{'sepal_length': {0: 5.1,
  1: 4.9,
  2: 4.7,
  3: 4.6,
  4: 5.0,
  5: 5.4,
  6: 4.6,
  7: 5.0,
  8: 4.4,
  9: 4.9,
  10: 5.4,
  11: 4.8,
  12: 4.8,
  13: 4.3,
  14: 5.8,
  15: 5.7,
  16: 5.4,
  17: 5.1,
  18: 5.7,
  19: 5.1,
  20: 5.4,
  21: 5.1,
  22: 4.6,
  23: 5.1,
  24: 4.8,
  25: 5.0,
  26: 5.0,
  27: 5.2,
  28: 5.2,
  29: 4.7,
  30: 4.8,
  31: 5.4,
  32: 5.2,
  33: 5.5,
  34: 4.9,
  35: 5.0,
  36: 5.5,
  37: 4.9,
  38: 4.4,
  39: 5.1,
  40: 5.0,
  41: 4.5,
  42: 4.4,
  43: 5.0,
  44: 5.1,
  45: 4.8,
  46: 5.1,
  47: 4.6,
  48: 5.3,
  49: 5.0,
  50: 7.0,
  51: 6.4,
  52: 6.9,
  53: 5.5,
  54: 6.5,
  55: 5.7,
  56: 6.3,
  57: 4.9,
  58: 6.6,
  59: 5.2,
  60: 5.0,
  61: 5.9,
  62: 6.0,
  63: 6.1,
  64: 5.6,
  65: 6.7,
  66: 5.6,
  67: 5.8,
  68: 6.2,
  69: 5.6,
  70: 5.9,
  71: 6.1,
  72: 6.3,
  73: 6.1,
  74: 6.4,
  75: 6.6,
  76: 6.8,
  77: 6.7,
  78: 6.0,
  79: 5.7,
  80: 5.5,
  81: 5.5,
  82: 5.8,
  83: 6.0,
  84: 5.4,
  85: 6.0,
  86: 6.7,
  87: 6.3,
  88: 5.6,
  89: 5.5,
  90

In [14]:
# 2. sepal_length , sepal_width, petal_length, petal_width를 모두 더한 'total_sum' 열을 데이터프레임에 추가하시오.
df['total_sum'] = df['sepal_width'] + df['sepal_length'] + df['petal_length'] + df['petal_width']
df.head()

sepal_length  sepal_width  petal_length  petal_width species  total_sum
0           5.1          3.5           1.4          0.2  setosa       10.2
1           4.9          3.0           1.4          0.2  setosa        9.5
2           4.7          3.2           1.3          0.2  setosa        9.4
3           4.6          3.1           1.5          0.2  setosa        9.4
4           5.0          3.6           1.4          0.2  setosa       10.2

In [23]:
# 3. 데이터프레임에서 인덱스가 짝수인 행만 추출하여 df_even 변수에 저장 후 기술통계량을 확인하시오.
df_even = df.iloc[range(0,len(df),2)]
df_even

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
6             4.6          3.4           1.4          0.3     setosa   
8             4.4          2.9           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
140           6.7          3.1           5.6          2.4  virginica   
142           5.8          2.7           5.1          1.9  virginica   
144           6.7          3.3           5.7          2.5  virginica   
146           6.3          2.5           5.0          1.9  virginica   
148           6.2          3.4           5.4          2.3  virginica   

     total_sum  
0         10.2  
2          9.4  
4         10.2  
6          9.7  
8          8.9  
..         ...  
140       17.8  
142       15.5  
144       18.2  
146       15.7  
148       17.3  

[75 rows x 6 columns]

In [24]:
df_even.describe()

sepal_length  sepal_width  petal_length  petal_width  total_sum
count      75.00000    75.000000      75.00000    75.000000  75.000000
mean        5.84000     3.064000       3.77600     1.218667  13.898667
std         0.80589     0.435468       1.78294     0.790773   3.079641
min         4.40000     2.000000       1.00000     0.100000   8.900000
25%         5.15000     2.800000       1.60000     0.250000  10.750000
50%         5.80000     3.000000       4.50000     1.300000  14.400000
75%         6.45000     3.400000       5.10000     1.850000  16.350000
max         7.70000     4.100000       6.90000     2.500000  19.500000

#### 구남이

In [30]:
import numpy as np
# 1. shape를 이용하여 행렬의 차원 알아보기
matrix = np.array([[4,2,1],[5,2,6],[1,1,1]])
matrix.shape

(3, 3)

In [34]:
# 2. numpy 배열 n을 3*5행렬로 재구성하기
n = np.arange(start=0, stop=15)
n = n.reshape(3,5)
n.shape , n

((3, 5),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

In [39]:
# 3. array1을 내림차순으로 정렬하기
array1 = np.random.randint(0, 10, size = 10)
array1 = np.sort(array1)[::-1]
array1

array([9, 9, 8, 7, 6, 5, 4, 3, 0, 0])

#### 강수민

In [45]:
# Q1. 0 부터 8까지의 값으로 3*3 행렬을 생성하라
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
# Q2. a를 생성하고 a의 마지막 열을 기준으로 오름차순으로 정렬해 새로운 행렬을 생성하라
a = np.random.randint(25, size=[5,5])
a = a[np.argsort(a[:,-1])]
print(a)

[[10  5  9 14  3]
 [19 20  0 22 14]
 [23  5 16 11 19]
 [ 0 11 10 15 21]
 [23  4  7 13 22]]


In [96]:
# Q3. 2번에서 생성한 새로운 행렬의 전치행렬을 구하고, 해당 행렬을 DataFrame으로 변환해라 
# (column명은 'a' 부터 'e'까지로 설정)
import pandas as pd
col_names = ['a','b','c','d','e']
df = pd.DataFrame(np.transpose(a),columns= col_names)
df

a   b   c   d   e
0  10  19  23   0  23
1   5  20   5  11   4
2   9   0  16  10   7
3  14  22  11  15  13
4   3  14  19  21  22

#### 박민영

In [97]:
# 문제 1
# 크기 10인 Null 벡터를 생성하되, 다섯 번째 값은 1으로 하는 벡터를 출력하라.
# 단, 데이터 값 타입은 int32로 지정하라.
array1 = np.zeros(10, dtype=np.int32)
array1[4] = 1
array1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [99]:
# 문제 2
# 8 * 8 행렬을 생성하여 체크보드 패턴으로 채워라.
# 자세한 형태는 아래와 같다.
# 0 1 0 1 0 1 ..
# 1 0 1 0 1 0 ..
# 0 1 0 1 0 1 ..
array1 = np.zeros((8,8), dtype=np.int32)
for i in range(0,8):
    if i % 2 == 0:
        j = range(1,8,2)
        array1[i,j] = 1
    else:
        j = range(0,8,2)
        array1[i,j] = 1
array1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [101]:
# 다른 풀이
array1 = np.zeros((8,8), dtype=np.int32)
array1[1::2, ::2] = 1
array1[::2, 1::2] = 1
array1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [108]:
# 문제 3
# 0 ~ 24로 이루어진 배열을 5 * 5 크기로 변환한 후 해당 배열의 1행과 2행을 바꾸어라.
array = np.arange(0,25).reshape(5,5)
array[[0,1]] = array[[1,0]]
array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
# 문제 4
# 아래의 a 배열을 열 방향으로 기준으로 정렬하라.
a = np.random.randint(0, 10, (3, 3)) # 0 ~ 10 사이의 숫자에서 랜덤추출한 (3, 3) 배열
np.sort(a,axis=1)

array([[7, 9, 9],
       [4, 6, 7],
       [5, 7, 8]])

In [94]:
# 문제 5
# X 행렬이 아래와 같을 때 행렬 인덱싱을 사용하여 4의 배수만을 선택하라.
X = np.array([[1,1,1,1], [1,2,4,8], [1,3,5,7],[1,4,16,32],[1,5,9,13]])
X[[X % 4 == 0]]

<ipython-input-94-d4b120efa3a7>:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  X[[X % 4 == 0]]


array([ 4,  8,  4, 16, 32])